# Generated by Django 2.2.7 on 2019-12-24 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191224_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished_on',
            new_name='published_on',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 6, 30, 18, 256106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 6, 30, 18, 255710, tzinfo=utc)),
        ),
    ]
