# Generated by Django 2.2.7 on 2019-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
